In [1]:
import torch

In [2]:
a = torch.tensor([1,2,3],dtype=int)

In [3]:
print(a)

tensor([1, 2, 3])


In [4]:
a.dtype #查看数据类型

torch.int64

In [5]:
b = torch.tensor([4,5,6],dtype=float)

In [6]:
print(b)

tensor([4., 5., 6.], dtype=torch.float64)


In [7]:
tensor = torch.tensor([[1,2,3],
                       [4,5,6]])

In [8]:
tensor.ndim #查看维度

2

In [9]:
tensor.shape #数据的形状

torch.Size([2, 3])

In [10]:
tensor.size()

torch.Size([2, 3])

In [11]:
tensor = torch.tensor([[1,2,3]])

In [12]:
tensor.size()

torch.Size([1, 3])

In [13]:
tensor = torch.tensor([1,2,3])

In [14]:
tensor.size()

torch.Size([3])

In [15]:
tensor = torch.tensor([1,2,3])

In [16]:
print(tensor.dim())# 用括号的层数判断维数
print(tensor.shape)# 每去掉一层括号，数暴露在外面的 “ , ”的个数+1来判断shape

1
torch.Size([3])


In [17]:
tensor = torch.tensor([[1,2,3],
                       [4,5,6]])

In [18]:
print(tensor.dim())
print(tensor.shape)

2
torch.Size([2, 3])


In [19]:
tensor = torch.tensor([[[1,1,1],[2,3,4]],
                       [[2,2,2],[3,3,3]],
                       [[2,2,2],[3,3,3]]])

In [20]:
print(tensor.dim())
print(tensor.shape)

3
torch.Size([3, 2, 3])


In [21]:
tensor = torch.tensor(1)

In [22]:
print(tensor.dim())
print(tensor.shape)

0
torch.Size([])


In [23]:
tensor = torch.tensor([1,2,4,3,5,6,7,8,9,0])

In [24]:
tensor.shape

torch.Size([10])

In [25]:
tensor = tensor.reshape(-1,1)

In [26]:
tensor.dim()

2

In [27]:
tensor.shape

torch.Size([10, 1])

In [28]:
tensor

tensor([[1],
        [2],
        [4],
        [3],
        [5],
        [6],
        [7],
        [8],
        [9],
        [0]])

In [29]:
tensor = torch.zeros(tensor.shape[0],10).scatter(1,tensor,1)

In [30]:
tensor

tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
tensor.shape

torch.Size([10, 10])

In [41]:
tensor = torch.tensor([10])

In [42]:
tensor

tensor([10])

In [43]:
tensor.item()

10