In [2]:
import numpy as np

In [9]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[2,2,3]])
arr3=np.arange(10)
arr4=np.arange(10,20)
arr5=np.arange(10,20,2)
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[1 2 3]
[[1 2 3]
 [2 2 3]]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [10]:
print(arr2[0,1])

2


In [13]:
print(arr2[[0,1],[1,2]])#前面表示行，后面表示列，返回的是向量

[2 3]


In [15]:
arr6=np.arange(1,21).reshape(4,5)

In [16]:
print(arr6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [26]:
print(arr6[1:3,1:-1])#前面表示行，后面表示列，包前不包后，返回的是矩阵

[[ 7  8  9]
 [12 13 14]]


In [27]:
print(arr6[2,:])#提取第二行

[11 12 13 14 15]


In [28]:
print(arr6[1:3,:])#提取第二、三行

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [30]:
print(arr6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [29]:
print(arr6[:,1:3])#提取第二、三列

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


In [31]:
print(arr6[:,1])#提取第二列，以向量输出

[ 2  7 12 17]


In [32]:
print(arr6[:,1].reshape(-1,1))#将行升级为列

[[ 2]
 [ 7]
 [12]
 [17]]


In [33]:
arr7=np.arange(10).reshape(2,5)

In [34]:
print(arr7)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [35]:
print(arr7.T)#矩阵的转置

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [39]:
arr8=np.arange(10).reshape(-1,1)#注意要将向量转化为矩阵

In [40]:
print(arr8)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [41]:
print(arr8.T)

[[0 1 2 3 4 5 6 7 8 9]]


In [42]:
arr9=np.arange(10).reshape(2,5)
print(arr9)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [46]:
arr10=np.arange(10).reshape(5,-1)
print(arr10)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [49]:
print(np.dot(arr9,arr10))#矩阵的乘法

[[ 60  70]
 [160 195]]
