In [1]:
import torch

In [3]:
sample = torch.rand(3,2)
sample

tensor([[0.6889, 0.8142],
        [0.1779, 0.8953],
        [0.9393, 0.5599]])

In [4]:
torch.sum(sample)

tensor(4.0755)

In [5]:
torch.min(sample)

tensor(0.1779)

In [6]:
torch.max(sample)

tensor(0.9393)

In [8]:
torch.argmin(sample) #求最小值所在的索引

tensor(2)

In [9]:
torch.argmax(sample)

tensor(4)

In [10]:
torch.mean(sample)

tensor(0.6793)

In [11]:
torch.median(sample) #排列后求中位数

tensor(0.6889)

In [12]:
torch.sqrt(sample)

tensor([[0.8300, 0.9023],
        [0.4217, 0.9462],
        [0.9692, 0.7483]])

In [13]:
sample**2

tensor([[0.4746, 0.6630],
        [0.0316, 0.8016],
        [0.8823, 0.3135]])