In [1]:
import torch

In [2]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.rand(3,4)

tensor([[0.8610, 0.1822, 0.6244, 0.4107],
        [0.8897, 0.2874, 0.9802, 0.4240],
        [0.5834, 0.1000, 0.7640, 0.7414]])

In [5]:
torch.randint(0,10,(2,3))

tensor([[6, 0, 5],
        [3, 6, 1]])

In [6]:
torch.randn(3,4)

tensor([[ 1.4000, -0.3005, -0.2812, -0.1760],
        [-0.8323, -0.8085, -0.0429,  0.3613],
        [ 0.6694,  0.1997,  0.2740,  0.5542]])

In [7]:
a = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])

In [8]:
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
b = torch.rand_like(a,dtype=float)
b

tensor([[0.4842, 0.6626],
        [0.7254, 0.5098],
        [0.1403, 0.0259]], dtype=torch.float64)

In [10]:
c = b.view(6) #修改数据的形状 等同于reshape()
c

tensor([0.4842, 0.6626, 0.7254, 0.5098, 0.1403, 0.0259], dtype=torch.float64)

In [11]:
c.shape

torch.Size([6])

In [12]:
d = b.view(2,3)
d

tensor([[0.4842, 0.6626, 0.7254],
        [0.5098, 0.1403, 0.0259]], dtype=torch.float64)

In [13]:
d = b.reshape(6)
d

tensor([0.4842, 0.6626, 0.7254, 0.5098, 0.1403, 0.0259], dtype=torch.float64)

In [14]:
d[1]

tensor(0.6626, dtype=torch.float64)

In [15]:
d[1].item() #把tensor转换为python环境里面的值

0.6625924684540931

In [16]:
import numpy as np

In [19]:
e = np.array(d)
e

array([0.48424473, 0.66259247, 0.72542659, 0.50984249, 0.14033277,
       0.02592745])

In [20]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [21]:
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3], dtype=torch.int32)