In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[10,100,1000]])

In [3]:
print(arr)

[[   1    2    3]
 [  10  100 1000]]


In [4]:
print(np.log(arr))#表示ln()

[[0.         0.69314718 1.09861229]
 [2.30258509 4.60517019 6.90775528]]


In [5]:
print(np.log(arr)/np.log(10))#表示lg()

[[0.         0.30103    0.47712125]
 [1.         2.         3.        ]]
